/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Advent_of_code_2018;

import Advent_of_code_2018.days.Day;
import Advent_of_code_2018.days.day1.Day1;
import org.junit.Test;
import static org.junit.Assert.*;

public class D1Test {
    @Test public void ex1() {
        String input = "+1\n+1\n+1";
        int expected = 3;
        Day sut = new Day1();

        assertEquals(expected, sut.getResultP1(input));
    }

    @Test public void D1p2() {
        String input = "+3\n+3\n+4\n-2\n-4";
        int expected = 10;
        Day sut = new Day1();

        assertEquals(expected, sut.getResultP2(input));
    }

    @Test public void D1p2t2() {
        String input = "-6\n+3\n+8\n+5\n-6";
        int expected = 5;
        Day sut = new Day1();

        assertEquals(expected, sut.getResultP2(input));
    }


    @Test public void D1p2t3() {
        String input = "+7\n+7\n-2\n-7\n-4";
        int expected = 14;
        Day sut = new Day1();

        assertEquals(expected, sut.getResultP2(input));
    }



}
