/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Advent_of_code_2018;

import Advent_of_code_2018.days.Day;
import Advent_of_code_2018.days.day2.Day2;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class D2Test {
    @Test public void p1() {
        String input = "abcdef\n" +
                "bababc\n" +
                "abbcde\n" +
                "abcccd\n" +
                "aabcdd\n" +
                "abcdee\n" +
                "ababab";
        int expected = 12;
        Day sut = new Day2();

        assertEquals(expected, sut.getResultP1(input));
    }

    @Test public void p1t2() {
        String input = "bababc";
        int expected = 1;
        Day sut = new Day2();
        var countMap = ((Day2) sut).countChars(input);
        assertEquals(expected, ((Day2) sut).count(3, countMap));
        assertEquals(expected, ((Day2) sut).count(2, countMap));
    }

    @Test public void p1t3() {
        String input = "abbcde";
        Day sut = new Day2();
        var countMap = ((Day2) sut).countChars(input);
        assertEquals(0, ((Day2) sut).count(3, countMap));
        assertEquals(1, ((Day2) sut).count(2, countMap));
    }

    @Test public void p2() {
        Day sut = new Day2();
        String input = "abcde\n" +
                "fghij\n" +
                "klmno\n" +
                "pqrst\n" +
                "fguij\n" +
                "axcye\n" +
                "wvxyz";
        String expected = "fgij";
        assertEquals(expected, sut.getResultP2(input));
    }

    @Test public void diffByOne() {
        var sut = new Day2();
        String a = "apa";
        String b = "ape";
        assertTrue(sut.isDiffByOne(a, b));
    }

    @Test public void notDiffByOne() {
        var sut = new Day2();
        String a = "apa";
        String b = "epe";
        assertFalse(sut.isDiffByOne(a, b));
    }
}
